# Build matrix
language: node_js
matrix:
  include:

    # Run linter once
    - node_js: '10'
      env: LINT=true

    # Run tests
    - node_js: '10'
    - node_js: '12'
    - node_js: '14'

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.x$/
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'if [ $LINT ]; then make verify; fi'
  - 'if [ ! $LINT ]; then make test; fi'
